"""Cambios en el modelo de client

Revision ID: 3013ec254732
Revises: 41bb60a20692
Create Date: 2025-11-28 11:51:51.210181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3013ec254732'
down_revision: Union[str, Sequence[str], None] = '41bb60a20692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'delete_reason')
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
